# Generated by Django 3.1.5 on 2021-02-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat_id',
            field=models.IntegerField(),
        ),
    ]
