# Generated by Django 3.1.5 on 2021-02-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210208_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('eircode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('date_placed', models.DateField()),
                ('time_placed', models.TimeField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=5000)),
                ('manufacturer', models.CharField(max_length=200)),
                ('stock_level', models.IntegerField()),
                ('next_shipment', models.DateField()),
            ],
        ),
    ]
