# Generated by Django 3.1.5 on 2021-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_customers_orders_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('date_placed', models.DateField()),
                ('time_placed', models.TimeField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prod_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
