# Generated by Django 3.1.5 on 2021-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20210210_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
