# Generated by Django 3.1.7 on 2021-03-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
    ]
