# Generated by Django 3.1.7 on 2021-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_product_prod_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_pic',
            field=models.CharField(default='Picture Not Found', max_length=150),
            preserve_default=False,
        ),
    ]
