# Generated by Django 3.1.5 on 2021-03-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_product_prod_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=500)),
            ],
        ),
    ]
