# Generated by Django 3.1.5 on 2021-03-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
