# Generated by Django 3.1.7 on 2021-03-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_shoppingbasket_shoppingbasketitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
