# Generated by Django 3.1.7 on 2021-03-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20210312_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
    ]
