# Generated by Django 3.1.7 on 2021-03-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20210312_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='shipping_addr',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.order'),
            preserve_default=False,
        ),
    ]
